### PR TITLE
Removed all thresholds except time

### PR DESCRIPTION
**Pull request by p8gonzal**
## Summary

Address Issue #1118. Removes all thresholds except time, still determined by API call.

## Changelog

[CATEGORY] [TYPE] - Message
[General][Change] - Removed device type & distance threshold for logging BT devices.

## Test Plan

Frequency of BT logs should increase and align with time specification in S3.

### CODE REVIEW

**Review by kevdesilva01 — APPROVED** [review]
ANDROID:
Onboarding login works as expected: PASS
Profile login works as expected: PASS
Profile logout works as expected: PASS
Home view logged out displays visitor cards: PASS
Home view logged in displays authenticated cards: FAIL (When logging into employee account the MyStudentChart and MyUCSDChart both appear on the home screen)
Native Scanner Code128 submission successful: PASS
Native Scanner 2D submission successful: PASS
Web Scanner Code128 submission successful: PASS
Web Scanner 2D submission successful: PASS
DM Push Notification received and appears in the Notifications tab: PASS
TM Push Notification received and appears in the Notifications tab: PASS

IOS:
Onboarding login works as expected: PASS
Profile login works as expected: PASS
Profile logout works as expected: PASS
Home view logged out displays visitor cards: PASS
Home view logged in displays authenticated cards: FAIL (When logging into employee account the MyStudentChart and MyUCSDChart both appear on the home screen)
Native Scanner Code128 submission successful: PASS
Native Scanner 2D submission successful: PASS
Web Scanner Code128 submission successful: PASS
Web Scanner 2D submission successful: PASS
DM Push Notification received and appears in the Notifications tab: PASS
TM Push Notification received and appears in the Notifications tab: PASS

**Comment by a6wu** [comment]
@kevdesilva01  How's the device battery life for this PR?

**Comment by kevdesilva01** [comment]
@a6wu I'm not sure at the moment but I can test that out on several devices and find out.

**Comment by kevdesilva01** [comment]
@a6wu no significant effect on battery life.

iPhone 11 - one year old
	With app open:
		98% at 9:45am
		94% at 10:45am 
		**4% in an hour**
	With app minimized but phone screen on:
		91% at 11:00am
		90% at 12:00pm
		**1% in an hour**

Motorola g7 Power - 2 months old
	With app open:
		100% at 1:45pm
		99:% at 2:45pm
		**1% in an hour**
	With app minimized but phone screen on:
		99% at 2:45pm
		99% at  3:35pm
		**0% in an hour**

**Review by c3bryant — APPROVED** [review]

**Pull request merged**
