### PR TITLE
Scandit Native Integration

### PR DESCRIPTION
**Pull request by gmihir**
## Summary

The existing native scanner solution was not effective on 2D color inverted data matrix codes.

## Changelog

[General] [Add] - Support for Scandit scanning on iOS and Android with color inversion enabled by default for data matrix codes.

### CODE REVIEW

**Review by c3bryant — CHANGES_REQUESTED** [review]
A few changes when time permits:
1. Deprecate/remove the barcode_scan package
2. Migrate cards/scanner/scanner_view to cards/native_scanner/native_scanner_view

**Review by c3bryant — CHANGES_REQUESTED** [review]
3. Incorporate web scanner logic for response code 409 - duplicate scan

4. Camera permission request on Android is not firing off.
  - 3 of 3 Android devices tested launched the scanner with a black screen. Manually providing camera permission in Settings resolves the issue.

**Comment by gmihir** [comment]
I will start working on this soon. Thanks Charles

**Comment by gmihir** [comment]
The requested changes are complete, ready for further testing.

**Review by c3bryant — APPROVED** [review]

**Pull request merged**
