### PR TITLE
Add isLoggedIn Event to Firebase Analytics

### PR DESCRIPTION
**Pull request by asg003**
## Summary
Added a custom isLoggedIn event and loggedOut for Firebase Analytics. 

## Changelog
[General] [Add] - added a isLoggedIn event in the Onboarding and Profile Login widgets. Added a loggedOut event for the Profile Logout button

## Test Plan
Tested on Android simulator but requires further testing with Firebase Analytics dashboard

### CODE REVIEW

**Review by g9singh — CHANGES_REQUESTED** [review]
This logic should be moved to the user data provider. If the logic remains here then the only events that will be tracked by firebase will be when the user manually logs in. It will not account for when the app re-authenticates the user using a silent login method or a refresh token method. The entire app uses the login and logout methods within the user data provider so this logic should be housed there as well.

**Review by g9singh — COMMENTED** [review]
The calls to firebase analytics would be better suited in the silent login and logout methods in lib/core/providers/user.dart

That way we can record the last time the user re-authenticated rather than just hit the login button.

**Comment by g9singh** [comment]
Needs to be resubmitted. Comments left in the PR.

**Comment by asg003** [comment]
moved Firebase login/logout events to user data provider in commit [f7304da](https://github.com/asg003/campus-mobile/commit/f7304da04eafb24fb61d7ccc57741ee64f503fb0)

**Review by c3bryant — APPROVED** [review]

**Review by c3bryant — APPROVED** [review]

**Pull request merged**
